TiktokLarge:
  data_root: ./data/TiktokLarge
  data_format: csv
  train_data: ./data/TiktokLarge/train.csv
  valid_data: ./data/TiktokLarge/valid.csv
  test_data: ./data/TiktokLarge/test.csv
  min_categr_count: 10
  feature_cols:
    [ { name: ['uid', 'item_id', 'author_id', 'item_city',
              'channel', 'music_id', 'device_id', 'video_duration'],
        active: True, dtype: str, type: categorical } ]
  label_col: [ { name: finish, dtype: float },
                { name: like, dtype: float } ]
  group_id: 'uid'

MerRec:
  data_root: ./data/MerRec
  data_format: csv
  train_data: ./data/MerRec/train.csv
  valid_data: ./data/MerRec/valid.csv
  test_data: ./data/MerRec/test.csv
  min_categr_count: 1
  feature_cols:
    [ { name: ['user_id', 'item_add_to_cart_tap', 'offer_make', 'buy_start', 'buy_comp',
              'c0_id', 'c1_id', 'c2_id', 'brand_id', 'item_condition_id', 'size_id', 'shipper_id',
              'hist_1', 'hist_2', 'hist_3', 'hist_4', 'hist_5', 'hist_6', 'hist_7',
              'sequence_id', 'session_id', 'product_id', 'color'],
        active: True, dtype: str, type: categorical },
      { name: ['price'],
        active: True, dtype: float, type: numeric } ]
  label_col: [ { name: item_view, dtype: int },
                { name: item_like, dtype: int } ]
  group_id: 'user_id'